# Generated by Django 4.0.6 on 2023-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_payment_razorpay_order_id_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
