# Generated by Django 4.0.6 on 2023-03-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_myuser_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
