# Generated by Django 4.0.6 on 2023-03-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_address_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
