# Generated by Django 4.0.6 on 2023-03-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
