# Generated by Django 4.0.6 on 2023-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_address_last_login_remove_address_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='email',
            new_name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.TextField(default=None),
        ),
    ]
