# Generated by Django 4.0.6 on 2023-04-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_email_address_user_address_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
